services:

  postgres:
    image: postgres:18
    container_name: loan-origination-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: loan_origination
      POSTGRES_USER: loan_app
      POSTGRES_PASSWORD: loan_app

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: