quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=loan_app
quarkus.datasource.password=loan_app
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/loan_origination

quarkus.hibernate-orm.database.generation=validate

quarkus.flyway.migrate-at-start=true