package com.loanorigination.riskassessment.domain;

/**
 * Código estructurado de la razón de la decisión.
 *
 * No guardamos solamente un texto libre porque estos códigos pueden
 * ser utilizados posteriormente para auditoría, métricas y reporting.
 */
public enum RiskAssessmentReasonCode {

    APPROVED_BY_DEVELOPMENT_POLICY,
    REFERRED_BY_DEVELOPMENT_POLICY,
    REJECTED_BY_DEVELOPMENT_POLICY,
    ELIGIBLE_BY_BASELINE_POLICY,
    UNSUPPORTED_PRODUCT,
    UNSUPPORTED_CURRENCY,
    TERM_EXCEEDS_POLICY,
    AMOUNT_EXCEEDS_POLICY,
    MANUAL_REVIEW_REQUIRED,
    APPROVED_BY_CREDIT_RISK_POLICY,
    REFERRED_BY_CREDIT_RISK_POLICY,
    REJECTED_BY_CREDIT_RISK_POLICY,
    AMOUNT_OUTSIDE_POLICY,
    TERM_OUTSIDE_POLICY,
    INSUFFICIENT_INCOME,
    HIGH_PROJECTED_DTI,
    LOW_DISPOSABLE_INCOME,
    HIGH_PAYMENT_TO_INCOME,
    LIMITED_EMPLOYMENT_STABILITY,
    STRONG_AFFORDABILITY,
    LOW_DEBT_BURDEN,
    SCORE_BELOW_APPROVAL_THRESHOLD,
    ELIGIBLE_BY_POLICY,
    STABLE_EMPLOYMENT,
    ESTABLISHED_SELF_EMPLOYMENT,
    HEALTHY_DISPOSABLE_INCOME,
    ADEQUATE_DISPOSABLE_INCOME,
    HIGH_EXISTING_DTI,
    LOW_LOAN_TO_INCOME,
    HIGH_LOAN_TO_INCOME,
    LONG_TERM_EXPOSURE
}
