package com.loanorigination.audit.domain;

public enum AuditAction {
    APPLICATION_SUBMITTED, RISK_ASSESSMENT_COMPLETED, APPLICATION_APPROVED, APPLICATION_REJECTED,
    OFFER_CREATED, OFFER_ACCEPTED, LOAN_CREATED, DISBURSEMENT_REQUESTED, LOAN_DISBURSED,
    REPAYMENT_SCHEDULE_CREATED
}
