import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { useAuth } from 'react-oidc-context'
import { api, errorMessage } from '../../shared/api/client'
import type { Disbursement, Installment, Loan, RepaymentSchedule } from '../../shared/types/api'
import { ConfirmDialog } from '../../shared/components/ConfirmDialog'
import { DateTime, FinancialGrid, FinancialValue, Money, PageHeader, Rate, Term } from '../../shared/components/Financial'
import { Empty, LoadingError, Notice } from '../../shared/components/Primitives'
import { StatusBadge } from '../../shared/components/StatusBadge'
import { Shell } from '../../shared/components/Shell'
import { rolesFromProfile } from '../../shared/auth/roles'
import styles from './LoanPage.module.css'

export function LoanPage() {
  const { id = '' } = useParams(); const auth = useAuth(); const token = auth.user?.access_token ?? ''; const roles = rolesFromProfile(auth.user?.profile); const operator = roles.includes('LOAN_OFFICER') || roles.includes('ADMIN')
  const [loan,setLoan]=useState<Loan|null>(null); const [disbursement,setDisbursement]=useState<Disbursement|null>(null); const [schedule,setSchedule]=useState<RepaymentSchedule|null>(null); const [installments,setInstallments]=useState<Installment[]|null>(null); const [error,setError]=useState(''); const [actionError,setActionError]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [confirm,setConfirm]=useState(false); const [reload,setReload]=useState(0)
  useEffect(()=>{if(!token||!id)return;let active=true;setLoan(null);setError('');api.loan(token,id).then(value=>{if(active)setLoan(value)}).catch(reason=>{if(active)setError(errorMessage(reason))});return()=>{active=false}},[token,id,reload])
  useEffect(()=>{if(!token||!loan)return;let active=true;api.disbursement(token,id).then(value=>{if(active)setDisbursement(value)}).catch(()=>{if(active)setDisbursement(null)});if(loan.status==='ACTIVE'||loan.status==='PAID_OFF'||loan.status==='DEFAULTED'){api.schedule(token,id).then(value=>{if(active)setSchedule(value)}).catch(()=>{if(active)setSchedule(null)});api.installments(token,id).then(value=>{if(active)setInstallments(value)}).catch(()=>{if(active)setInstallments(null)})}return()=>{active=false}},[token,id,loan,reload])
  const startDisbursement=async()=>{setBusy(true);setActionError('');setMessage('');try{const value=await api.disburse(token,id);setDisbursement(value);setMessage(`Desembolso ${value.status}.`);setReload(v=>v+1)}catch(reason){setActionError(errorMessage(reason))}finally{setBusy(false);setConfirm(false)}}
  return <Shell role={roles.includes('ADMIN')?'ADMIN':operator?'LOAN_OFFICER':'CUSTOMER'}><PageHeader eyebrow={operator?'OPERACIONES':'PORTAL DEL CLIENTE'} title="Detalle del préstamo" description="Estado financiero, desembolso y calendario de cuotas." action={loan?<StatusBadge value={loan.status}/>:undefined}/>{loan?<><section className={styles.card}><div className={styles.amount}><Money value={loan.principal} currency={loan.currency}/><span>Capital</span></div><FinancialGrid><FinancialValue label="Estado"><StatusBadge value={loan.status}/></FinancialValue><FinancialValue label="Tasa anual"><Rate value={loan.annualInterestRatePercentage}/></FinancialValue><FinancialValue label="Plazo"><Term months={loan.termMonths}/></FinancialValue><FinancialValue label="Cuota mensual"><Money value={loan.monthlyInstallment} currency={loan.currency}/></FinancialValue><FinancialValue label="Total estimado"><Money value={loan.totalRepayment} currency={loan.currency}/></FinancialValue><FinancialValue label="Creado"><DateTime value={loan.createdAt}/></FinancialValue></FinancialGrid></section>
    <section className={styles.section}><div className={styles.sectionHeading}><div><h2>Desembolso</h2><p>Operado por el adapter local del backend.</p></div>{disbursement&&<StatusBadge value={disbursement.status}/>}</div><div className={styles.card}><FinancialGrid>{disbursement?<><FinancialValue label="Importe"><Money value={disbursement.amount} currency={disbursement.currency}/></FinancialValue><FinancialValue label="Solicitado"><DateTime value={disbursement.requestedAt}/></FinancialValue><FinancialValue label="Procesado"><DateTime value={disbursement.processingAt}/></FinancialValue><FinancialValue label="Completado"><DateTime value={disbursement.completedAt}/></FinancialValue><FinancialValue label="Fallido"><DateTime value={disbursement.failedAt}/></FinancialValue></>:<FinancialValue label="Estado">Aún no hay un desembolso registrado.</FinancialValue>}</FinancialGrid>{operator&&loan.status==='PENDING_DISBURSEMENT'&&<button className={styles.primary} disabled={busy} onClick={()=>setConfirm(true)}>{busy?'Procesando…':'Iniciar desembolso'}</button>}</div>{message&&<Notice>{message}</Notice>}{actionError&&<Notice>{actionError}</Notice>}</section>
    {loan.status==='ACTIVE'||loan.status==='PAID_OFF'||loan.status==='DEFAULTED'?<section className={styles.section}><div className={styles.sectionHeading}><div><h2>Plan de pagos</h2><p>{schedule?`${schedule.installmentCount} cuotas · desembolsado ${new Date(schedule.disbursedOn).toLocaleDateString('es-AR')}`:'Calendario de amortización generado al desembolsar.'}</p></div></div>{installments?.length?<div className={styles.tableWrap}><table><thead><tr><th>#</th><th>Vencimiento</th><th>Capital</th><th>Interés</th><th>Cuota</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>{installments.map(item=><tr key={item.id}><td>{item.installmentNumber}</td><td><DateTime value={item.dueDate} dateOnly/></td><td><Money value={item.principalAmount} currency={item.currency}/></td><td><Money value={item.interestAmount} currency={item.currency}/></td><td><strong><Money value={item.totalAmount} currency={item.currency}/></strong></td><td><Money value={item.remainingPrincipal} currency={item.currency}/></td><td><StatusBadge value={item.status}/></td></tr>)}</tbody></table></div>:installments?<Empty title="El calendario no tiene cuotas" text="El backend no devolvió cuotas para este calendario."/>:<LoadingError error={error||'Cargando el calendario…'}/>}</section>:null}
  </>:<LoadingError error={error||'Cargando el préstamo…'}/>}<ConfirmDialog open={confirm} title="Iniciar desembolso" description="Se solicitará el desembolso local para este préstamo. El backend administra el estado y registra la operación." confirmLabel="Confirmar desembolso" busy={busy} onCancel={()=>setConfirm(false)} onConfirm={()=>void startDisbursement()}/></Shell>
}
