ALTER TABLE audit_events DROP CONSTRAINT ck_audit_action;

ALTER TABLE audit_events
    ADD CONSTRAINT ck_audit_action CHECK (action IN (
        'APPLICATION_SUBMITTED',
        'RISK_ASSESSMENT_REQUESTED',
        'RISK_ASSESSMENT_COMPLETED',
        'FRAUD_ASSESSMENT_REQUESTED',
        'FRAUD_ASSESSMENT_COMPLETED',
        'FRAUD_CASE_RESOLVED',
        'APPLICATION_APPROVED',
        'APPLICATION_REJECTED',
        'OFFER_CREATED',
        'OFFER_ACCEPTED',
        'LOAN_CREATED',
        'DISBURSEMENT_REQUESTED',
        'LOAN_DISBURSED',
        'REPAYMENT_SCHEDULE_CREATED'
    ));
